### ISSUE TITLE
Dash (-) character not supported

### ISSUE THREAD

**Issue by kotac24** [hallsbyra/HallsByra.Code128#1]
The dash character is not supported and trying to encode barcode like "12456-asdf" throws exception. Looking into the definition.cs file it turns out a sneaky unicode character sneaked in that is looking same as dash but it i actually something else.
![image](https://github.com/hallsbyra/HallsByra.Code128/assets/23376915/7614c5ae-e7c9-4e7b-a60c-e95893bd4a2f)

**Comment by hallsbyra** [comment]
Fixed in 1.0.1.
